<?php

acf_add_local_field_group(array(
	'key' => 'group_545920dbb80dd',
	'title' => 'District Fields',
	'fields' => array(
		array(
			'key' => 'field_5459210f52e65',
			'label' => 'Superintendent',
			'name' => 'superintendent',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_549996dc6beff',
			'label' => 'Superintendent Email',
			'name' => 'superintendent_email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_54a1db4a374f5',
			'label' => 'Superintendent Picture',
			'name' => 'superintendent_picture',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => 0,
			'min_height' => 0,
			'min_size' => 0,
			'max_width' => 0,
			'max_height' => 0,
			'max_size' => 0,
			'mime_types' => '',
		),
		array(
			'key' => 'field_5459211a52e66',
			'label' => 'Street Address',
			'name' => 'address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_549996b56befd',
			'label' => 'Mailing Address',
			'name' => 'mailing_address',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5459212852e67',
			'label' => 'Phone Number',
			'name' => 'phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5459214552e68',
			'label' => 'Fax Number',
			'name' => 'fax',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_549998596bf02',
			'label' => 'Number of schools',
			'name' => 'number_of_schools',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5499986c6bf03',
			'label' => 'Number of students',
			'name' => 'number_of_students',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_54999874375d5',
			'label' => 'Number of teachers',
			'name' => 'number_of_teachers',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array(
			'key' => 'field_5e2f1a98fa08a',
			'label' => 'Links',
			'name' => 'group_links',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e2f1aa4fa08b',
					'label' => 'Website',
					'name' => 'website-group',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e2f1abcfa08c',
					'label' => 'School Board',
					'name' => 'school_board',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e2f1b659a4c9',
					'label' => 'Calendar',
					'name' => 'district_calendar_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e2f1ac0fa08d',
					'label' => 'Links',
					'name' => 'group_links_extra',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5e2f1b05b6429',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5e2f1b0bb642a',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5e2f2c49c4f23',
			'label' => 'Social Media Links',
			'name' => 'social_media_section',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5e2f2c49c4f24',
					'label' => 'Facebook',
					'name' => 'facebook-group',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e2f2c49c4f25',
					'label' => 'Twitter',
					'name' => 'twitter-group',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
				array(
					'key' => 'field_5e2f2c49c4f27',
					'label' => 'Links',
					'name' => 'group_links_extra',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array(
						array(
							'key' => 'field_5e2f2c49c4f28',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5e2f2c49c4f29',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
			),
		),
		array(
			'key' => 'field_5e2f2db3cd4be',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'district',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

// acf_add_local_field_group(array(
// 	'key' => 'group_545920dbb80dd',
// 	'title' => 'District Fields',
// 	'fields' => array(
// 		array(
// 			'key' => 'field_5459210f52e65',
// 			'label' => 'Superintendent',
// 			'name' => 'superintendent',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_549996ce6befe',
// 			'label' => 'Superintendent Phone',
// 			'name' => 'superintendent_phone',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_549996dc6beff',
// 			'label' => 'Superintendent Email',
// 			'name' => 'superintendent_email',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_54a1db4a374f5',
// 			'label' => 'Superintendent Picture',
// 			'name' => 'superintendent_picture',
// 			'type' => 'image',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'return_format' => 'url',
// 			'preview_size' => 'thumbnail',
// 			'library' => 'all',
// 			'min_width' => 0,
// 			'min_height' => 0,
// 			'min_size' => 0,
// 			'max_width' => 0,
// 			'max_height' => 0,
// 			'max_size' => 0,
// 			'mime_types' => '',
// 		),
// 		array(
// 			'key' => 'field_5459211a52e66',
// 			'label' => 'Street Address',
// 			'name' => 'address',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => 'br',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_549996b56befd',
// 			'label' => 'Mailing Address',
// 			'name' => 'mailing_address',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => 'br',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_5459212852e67',
// 			'label' => 'Phone Number',
// 			'name' => 'phone',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_5459214552e68',
// 			'label' => 'Fax Number',
// 			'name' => 'fax',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_545920e552e64',
// 			'label' => 'Website',
// 			'name' => 'website',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_551458851fc50',
// 			'label' => 'Academic calendar URL',
// 			'name' => 'academic_calendar_url',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_5514589b1fc51',
// 			'label' => 'District calendar URL',
// 			'name' => 'district_calendar_url',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_551458a31fc52',
// 			'label' => 'District calendar iCal feed',
// 			'name' => 'district_calendar_ical_feed',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_5499982d6bf00',
// 			'label' => 'Twitter username',
// 			'name' => 'twitter',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_551458580ee24',
// 			'label' => 'Facebook URL',
// 			'name' => 'facebook',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_551458c71fc54',
// 			'label' => 'YouTube URL',
// 			'name' => 'youtube',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_551458bd1fc53',
// 			'label' => 'Vimeo username',
// 			'name' => 'vimeo',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_551458ee1fc55',
// 			'label' => 'Vine URL',
// 			'name' => 'vine',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_551458fc1fc56',
// 			'label' => 'Instagram URL',
// 			'name' => 'instagram',
// 			'type' => 'url',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 		),
// 		array(
// 			'key' => 'field_5499983d6bf01',
// 			'label' => 'School board members',
// 			'name' => 'school_board_members',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => 'br',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_549998596bf02',
// 			'label' => 'Number of schools',
// 			'name' => 'number_of_schools',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_5499986c6bf03',
// 			'label' => 'Number of students',
// 			'name' => 'number_of_students',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_54999874375d5',
// 			'label' => 'Number of teachers',
// 			'name' => 'number_of_teachers',
// 			'type' => 'text',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'prepend' => '',
// 			'append' => '',
// 			'maxlength' => '',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_549998818f3d6',
// 			'label' => 'School board meetings',
// 			'name' => 'school_board_meetings',
// 			'type' => 'textarea',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'default_value' => '',
// 			'placeholder' => '',
// 			'maxlength' => '',
// 			'rows' => '',
// 			'new_lines' => 'br',
// 			'readonly' => 0,
// 			'disabled' => 0,
// 		),
// 		array(
// 			'key' => 'field_549998818f3e7',
// 			'label' => 'Links',
// 			'name' => 'links',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 0,
// 			'max' => 0,
// 			'layout' => 'table',
// 			'button_label' => 'Add Link',
// 			'sub_fields' => array(
// 				array(
// 					'key' => 'field_549998818f3e8',
// 					'label' => 'Name',
// 					'name' => 'name',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => 'field_549998818f3e9',
// 					'label' => 'URL',
// 					'name' => 'url',
// 					'type' => 'url',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 				),
// 			),
// 		),
// 		array(
// 			'key' => 'field_549998818f3f0',
// 			'label' => 'Social Media Links',
// 			'name' => 'social_media_links',
// 			'type' => 'repeater',
// 			'instructions' => '',
// 			'required' => 0,
// 			'conditional_logic' => 0,
// 			'wrapper' => array(
// 				'width' => '',
// 				'class' => '',
// 				'id' => '',
// 			),
// 			'collapsed' => '',
// 			'min' => 0,
// 			'max' => 0,
// 			'layout' => 'table',
// 			'button_label' => 'Add Link',
// 			'sub_fields' => array(
// 				array(
// 					'key' => 'field_549998818f3f1',
// 					'label' => 'Name',
// 					'name' => 'name',
// 					'type' => 'text',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 					'prepend' => '',
// 					'append' => '',
// 					'maxlength' => '',
// 				),
// 				array(
// 					'key' => 'field_549998818f3f2',
// 					'label' => 'URL',
// 					'name' => 'url',
// 					'type' => 'url',
// 					'instructions' => '',
// 					'required' => 0,
// 					'conditional_logic' => 0,
// 					'wrapper' => array(
// 						'width' => '',
// 						'class' => '',
// 						'id' => '',
// 					),
// 					'default_value' => '',
// 					'placeholder' => '',
// 				),
// 			),
// 		),
// 	),
// 	'location' => array(
// 		array(
// 			array(
// 				'param' => 'post_type',
// 				'operator' => '==',
// 				'value' => 'district',
// 			),
// 		),
// 	),
// 	'menu_order' => 0,
// 	'position' => 'normal',
// 	'style' => 'default',
// 	'label_placement' => 'top',
// 	'instruction_placement' => 'label',
// 	'hide_on_screen' => '',
// 	'active' => true,
// 	'description' => '',
// ));
